### ISSUE TITLE
[Request] Percentage support/more complex expressions

### ISSUE THREAD

**Issue by KaranTrivedi** [farski/blendstat-grafana#1]
Hello, 

This is an amazing plugin. Would it be possible to add us support for some  more math. i.e. query a+b-c, a/b *100 (percentage) etc.?

Thanks
Karan.

**Comment by farski** [comment]
@KaranTrivedi I don't have any plans to add that sort of functionality, but the [Singlestat Math](https://grafana.com/grafana/plugins/blackmirror1-singlestat-math-panel) plugin sounds very close to what you're looking for, so I would take a look at that and see if it offers what you need.

**Comment by KaranTrivedi** [comment]
Hey, thanks for the reply. This was for elastic, not influx, I dont think I can use that.

**Comment by farski** [comment]
Ah, hm. I took a look at the source for it and it looked fairly generic. I think it should work with any data source that outputs time series data. If not, I know that Grafana has had native query math support on the roadmap for quite a while. Hopefully that makes it into the product sometime soon.

**Comment by KaranTrivedi** [comment]
Alright, thanks.
