### ISSUE TITLE
Text is smaller than SingleStat panel

### ISSUE THREAD

**Issue by jonatanhost** [farski/blendstat-grafana#2]
These panels are both set to 200%.

![image](https://user-images.githubusercontent.com/11466166/68272258-5f5e4f80-0063-11ea-8648-dc1f6a50a8da.png)

**Comment by farski** [comment]
d53bf7c should resolve this issue

**Comment by farski** [comment]
@jonatanhost Did this get resolved in the most recent release of the plugin?

**Comment by jonatanhost** [comment]
@farski Yes it did
